version: '3.8'

# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./tests:/app/tests
    environment:
      - DEBUG=true
      - RELOAD=true
    command: ["python", "-m", "uvicorn", "src.production_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Development database for testing
  postgres:
    image: postgres:15-alpine
    container_name: rag-postgres-dev
    environment:
      - POSTGRES_USER=raguser
      - POSTGRES_PASSWORD=ragpass
      - POSTGRES_DB=ragdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: rag-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  # MinIO for S3-compatible storage testing
  minio:
    image: minio/minio:latest
    container_name: rag-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_dev:/data

volumes:
  postgres_data_dev:
  minio_data_dev: